import Head from "next/head";
import Navbar from "@/components/Navbar";
import Hero from "@/components/Hero";

export default function Home() {
	return (
		<>
			<Head>
				<title>Justin Scorzafava Portfolio</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className='bg-white px-10'>
				<section className='min-h-screen'>
					<Navbar />
					<Hero />
				</section>
				<section>
					<div>
						<h3 className='text-3xl pb-1 pt-8'>Services I offer</h3>
						<p className='text-md py-2 leading-8 text-gray-800'>
							Since the beginning of my journey as a web developer/designer, I've done
							remote work for
							<span className='text-teal-500'> agencies</span> consulted for{" "}
							<span className='text-teal-500'>local businesses</span> and collaborated
							with talented colleagues to create beautiful websites and mobile
							applications for both business and consumer use.
						</p>
						<p className='text-md py-2 leading-8 text-gray-800'>
							I offer a multitude of services, including programming for both web and
							mobile development.
						</p>
					</div>
				</section>
			</main>
		</>
	);
}
